language: python

python:
  - "3.7"

install:
    - pip install pipenv
    - pipenv install --dev --skip-lock

script:
    - flake8
    - black
    - pytest --check-links --ignore=docs/course_materials/reveal
