#!/usr/bin/env python3

import sys
import os

script_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.append(os.path.join(script_dir, "rose", "server"))


from rose.server import main
main.main()
