#!/usr/bin/env python

import sys
import xmlrpclib
from rtp.common import config

VERBS = ('start', 'stop')

def main():
    if len(sys.argv) != 2:
        usage('No verb specified')

    verb = sys.argv[1]
    if verb not in VERBS:
        usage('unknown verb: %r' % verb)

    url = 'http://127.0.0.1:%d/rpc2' % config.web_port
    server = xmlrpclib.Server(url)
    method = getattr(server, verb)
    try:
        method()
    except Exception as e:
        print e
        sys.exit(1)

def usage(msg):
    if msg:
        print msg
    print 'usage: %s [%s]' % (sys.argv[0], '|'.join(VERBS))
    sys.exit(2)

if __name__ == '__main__':
    main()
