#!/usr/bin/env python

import sys
import os
import xmlrpclib
from rtp.common import config

server_address = 'localhost'

class Client(object):

    def __init__(self, args):
        self.args = args
        url = 'http://%s:%d/rpc2' % (server_address, config.web_port)
        self.server = xmlrpclib.Server(url)

    def run(self):
        if len(sys.argv) < 2:
            self.usage('No verb specified')

        verb = self.args[1]
        method_name = 'do_' + verb.replace('-', '_')
        try:
            method = getattr(self, method_name)
        except AttributeError:
            self.usage('Unknown verb: %r' % verb)
        try:
            method()
        except Exception as e:
            print e
            sys.exit(1)

    def do_start(self):
        """start"""
        self.server.start()

    def do_stop(self):
        """stop"""
        self.server.stop()

    def do_set_rate(self):
        """set-rate RATE"""
        if len(self.args) < 3:
            self.usage("RATE required")
        rate = float(self.args[2])
        self.server.set_rate(rate)

    def commands(self):
        return sorted(getattr(self, name).__doc__
                      for name in dir(self)
                      if name.startswith('do_'))

    def usage(self, msg):
        if msg:
            print msg
        basename = os.path.basename(self.args[0])
        print 'Usage: %s [%s]' % (basename, '|'.join(self.commands()))
        sys.exit(2)

if __name__ == '__main__':
    Client(sys.argv).run()
